### ISSUE TITLE
Xenoblade 2 BDAT index now 404s

### ISSUE THREAD

**Issue by MACandCHEEZWIZ1** [Thealexbarney/xenoblade2-research#2]
I don't even quite know how to begin this, but thanks for all your efforts. The information you've dug up is really interesting and I've been using it extensively for the the past few weeks ever since I came across it.

It seems now that the whole directory (https://thealexbarney.github.io/xenoblade2-data/bdat/index.html) is missing. That might have been intentional on your part since at the time of writing, you were online a few hours ago and this is only a recent development. You can tell how much I value your work when I start panicking and make an account just to contact you over this, but I don't think I've ever seen material this extensive.

Anyway, thanks for this (and especially thanks for the Xenoblade X work you've started doing recently; I was hoping something similar existed as guide books don't even compare to a data mine).

**Comment by Thealexbarney** [comment]
The folder structure was moved around a little to accommodate having all 3 Xenoblade games. The [main page](https://thealexbarney.github.io/xenoblade2-data) now has links to each game.

The old index at https://thealexbarney.github.io/xenoblade2-data was moved [here](https://thealexbarney.github.io/xenoblade2-data/xb2/index.html).  
The page I think you were looking for was moved [here](https://thealexbarney.github.io/xenoblade2-data/xb2/bdat/index.html)

**Comment by MACandCHEEZWIZ1** [comment]
Thanks for the quick response. That's good to know it wasn't taken down or anything. I'm not that experienced with GitHub so I feel like maybe this was a non-issue for more experienced users who would have noticed something like that and changed their links appropriately. Once more, I appreciate your efforts for a comprehensive info dump and I hope I can promote the use and examination of that info by more people in a hopeful attempt to lessen the workload of examining thousands of files.
